import type { GalleryImage } from '@/types'

export const galleryImages: GalleryImage[] = [
  { id: '100', src: '/images/gallery/fotometro-wedding-100.jpg', alt: 'Fotografija vjenčanja Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '101', src: '/images/gallery/fotometro-wedding-101.jpg', alt: 'Fotografija vjenčanja BiH - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '102', src: '/images/gallery/fotometro-wedding-102.jpg', alt: 'Svadbeni fotograf Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '103', src: '/images/gallery/fotometro-wedding-103.jpg', alt: 'Profesionalna fotografija vjenčanja - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '104', src: '/images/gallery/fotometro-wedding-104.jpg', alt: 'Snimanje vjenčanja Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '105', src: '/images/gallery/fotometro-wedding-105.jpg', alt: 'Vjenčanje u Prijedoru fotograf - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '106', src: '/images/gallery/fotometro-wedding-106.jpg', alt: 'Najbolji fotograf za vjenčanja BiH - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '107', src: '/images/gallery/fotometro-wedding-107.jpg', alt: 'Ekskluzivna fotografija vjenčanja - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '108', src: '/images/gallery/fotometro-wedding-108.jpg', alt: 'Fotografisanje svadbi Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '109', src: '/images/gallery/fotometro-wedding-109.jpg', alt: 'Svadbeni trenuci Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '110', src: '/images/gallery/fotometro-wedding-110.jpg', alt: 'Fotografija mladenaca Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '111', src: '/images/gallery/fotometro-wedding-111.jpg', alt: 'Profesionalno snimanje svadbi - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '112', src: '/images/gallery/fotometro-wedding-112.jpg', alt: 'Vjenčanje Prijedor fotografije - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '113', src: '/images/gallery/fotometro-wedding-113.jpg', alt: 'Fotograf za vjenčanje Bosna - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '114', src: '/images/gallery/fotometro-wedding-114.jpg', alt: 'Najbolje fotografije vjenčanja Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '115', src: '/images/gallery/fotometro-wedding-115.jpg', alt: 'Svadbena fotografija Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '116', src: '/images/gallery/fotometro-wedding-116.jpg', alt: 'Fotografisanje vjenčanja Banja Luka - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '117', src: '/images/gallery/fotometro-wedding-117.jpg', alt: 'Snimanje dronom vjenčanja Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '118', src: '/images/gallery/fotometro-wedding-118.jpg', alt: 'Wedding photography Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '119', src: '/images/gallery/fotometro-wedding-119.jpg', alt: 'Wedding videography Bosnia - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '120', src: '/images/gallery/fotometro-wedding-120.jpg', alt: 'Fotografisanje mladenaca BiH - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '121', src: '/images/gallery/fotometro-wedding-121.jpg', alt: 'Luksuzno vjenčanje Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '122', src: '/images/gallery/fotometro-wedding-122.jpg', alt: 'Svadbeni studio Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '123', src: '/images/gallery/fotometro-wedding-123.jpg', alt: 'Vjenčanje iz snova Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '124', src: '/images/gallery/fotometro-wedding-124.jpg', alt: 'Profesionalna video produkcija vjenčanja - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '125', src: '/images/gallery/fotometro-wedding-125.jpg', alt: 'Filmsko snimanje vjenčanja Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '126', src: '/images/gallery/fotometro-wedding-126.jpg', alt: 'Snimanje svadbi dronom BiH - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '127', src: '/images/gallery/fotometro-wedding-127.jpg', alt: 'Wedding drone Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '128', src: '/images/gallery/fotometro-wedding-128.jpg', alt: 'Fotograf vjenčanja Sanski Most - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '129', src: '/images/gallery/fotometro-wedding-129.jpg', alt: 'Fotograf vjenčanja Kozarska Dubica - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '130', src: '/images/gallery/fotometro-wedding-130.jpg', alt: 'Fotograf vjenčanja Novi Grad - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '131', src: '/images/gallery/fotometro-wedding-131.jpg', alt: 'Fotograf vjenčanja Bosanska Krupa - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '132', src: '/images/gallery/fotometro-wedding-132.jpg', alt: 'Uspomene koje traju Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '133', src: '/images/gallery/fotometro-wedding-133.jpg', alt: 'Kreativna fotografija vjenčanja - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '134', src: '/images/gallery/fotometro-wedding-134.jpg', alt: 'Umjetnička fotografija Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '135', src: '/images/gallery/fotometro-wedding-135.jpg', alt: 'Fotografisanje proslava Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '136', src: '/images/gallery/fotometro-wedding-136.jpg', alt: 'Video snimanje proslava Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '137', src: '/images/gallery/fotometro-wedding-137.jpg', alt: 'Fotometrom do savršenih slika - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '138', src: '/images/gallery/fotometro-wedding-138.jpg', alt: 'Svadbeni video Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '139', src: '/images/gallery/fotometro-wedding-139.jpg', alt: 'Najljepši svadbeni momenti - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '140', src: '/images/gallery/fotometro-wedding-140.jpg', alt: 'Fotograf vjenčanja Laktaši - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '141', src: '/images/gallery/fotometro-wedding-141.jpg', alt: 'Fotograf vjenčanja Gradiška - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '142', src: '/images/gallery/fotometro-wedding-142.jpg', alt: 'Fotograf vjenčanja Prnjavor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '143', src: '/images/gallery/fotometro-wedding-143.jpg', alt: 'Fotograf vjenčanja Derventa - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '144', src: '/images/gallery/fotometro-wedding-144.jpg', alt: 'Vjenčanje u restoranu Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '145', src: '/images/gallery/fotometro-wedding-145.jpg', alt: 'Dekoracija vjenčanja Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '146', src: '/images/gallery/fotometro-wedding-146.jpg', alt: 'Svadbeni običaji Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '147', src: '/images/gallery/fotometro-wedding-147.jpg', alt: 'Portret mladenaca Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '148', src: '/images/gallery/fotometro-wedding-148.jpg', alt: 'Fotografisanje vjenčanja u prirodi - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '149', src: '/images/gallery/fotometro-wedding-149.jpg', alt: 'Romantično vjenčanje Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '150', src: '/images/gallery/fotometro-wedding-150.jpg', alt: 'Vjenčanje u crkvi Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '151', src: '/images/gallery/fotometro-wedding-151.jpg', alt: 'Vjenčanje u opštini Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '152', src: '/images/gallery/fotometro-wedding-152.jpg', alt: 'Svadbeni ples Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '153', src: '/images/gallery/fotometro-wedding-153.jpg', alt: 'Vatromet na vjenčanju Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '154', src: '/images/gallery/fotometro-wedding-154.jpg', alt: 'Svadbena torta Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '155', src: '/images/gallery/fotometro-wedding-155.jpg', alt: 'Gosti na vjenčanju Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '156', src: '/images/gallery/fotometro-wedding-156.jpg', alt: 'Atmosfera na vjenčanju Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '157', src: '/images/gallery/fotometro-wedding-157.jpg', alt: 'Zabava na vjenčanju Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '158', src: '/images/gallery/fotometro-wedding-158.jpg', alt: 'Muzika za vjenčanje Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '159', src: '/images/gallery/fotometro-wedding-159.jpg', alt: 'Svadbeni salon Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '160', src: '/images/gallery/fotometro-wedding-160.jpg', alt: 'Vjenčanje na otvorenom Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '161', src: '/images/gallery/fotometro-wedding-161.jpg', alt: 'Bidermajer Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '162', src: '/images/gallery/fotometro-wedding-162.jpg', alt: 'Burme Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '163', src: '/images/gallery/fotometro-wedding-163.jpg', alt: 'Vjenčanica Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '164', src: '/images/gallery/fotometro-wedding-164.jpg', alt: 'Odijelo za vjenčanje Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '165', src: '/images/gallery/fotometro-wedding-165.jpg', alt: 'Šminka za vjenčanje Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '166', src: '/images/gallery/fotometro-wedding-166.jpg', alt: 'Frizura za vjenčanje Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '167', src: '/images/gallery/fotometro-wedding-167.jpg', alt: 'Pripreme mladenaca Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '168', src: '/images/gallery/fotometro-wedding-168.jpg', alt: 'Prva bračna noć Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '169', src: '/images/gallery/fotometro-wedding-169.jpg', alt: 'Medeni mjesec Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '170', src: '/images/gallery/fotometro-wedding-170.jpg', alt: 'Porodična fotografija vjenčanja - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '171', src: '/images/gallery/fotometro-wedding-171.jpg', alt: 'Kumovi na vjenčanju Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '172', src: '/images/gallery/fotometro-wedding-172.jpg', alt: 'Djevojačko veče Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '173', src: '/images/gallery/fotometro-wedding-173.jpg', alt: 'Momčko veče Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '174', src: '/images/gallery/fotometro-wedding-174.jpg', alt: 'Svadbeni pokloni Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '175', src: '/images/gallery/fotometro-wedding-175.jpg', alt: 'Vjenčanje u restoranu 2 Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '176', src: '/images/gallery/fotometro-wedding-176.jpg', alt: 'Vjenčanje u restoranu 3 Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '177', src: '/images/gallery/fotometro-wedding-177.jpg', alt: 'Vjenčanje u restoranu 4 Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '178', src: '/images/gallery/fotometro-wedding-178.jpg', alt: 'Vjenčanje u restoranu 5 Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '179', src: '/images/gallery/fotometro-wedding-179.jpg', alt: 'Vjenčanje u restoranu 6 Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '180', src: '/images/gallery/fotometro-wedding-180.jpg', alt: 'Vjenčanje u restoranu 7 Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '181', src: '/images/gallery/fotometro-wedding-181.jpg', alt: 'Vjenčanje u restoranu 8 Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '182', src: '/images/gallery/fotometro-wedding-182.jpg', alt: 'Vjenčanje u restoranu 9 Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '183', src: '/images/gallery/fotometro-wedding-183.jpg', alt: 'Vjenčanje u restoranu 10 Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '184', src: '/images/gallery/fotometro-wedding-184.jpg', alt: 'Vjenčanje u restoranu 11 Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
  { id: '185', src: '/images/gallery/fotometro-wedding-185.jpg', alt: 'Vjenčanje u restoranu 12 Prijedor - Fotometro Wedding', width: 1200, height: 800, category: 'vjencanje' },
]
